In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3], [4,5,6]])

print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
len(b)

2

In [5]:
type(b[0])

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a

array([1, 2, 3])

In [9]:
a.shape

(3,)

In [10]:
a.dtype

dtype('int64')

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b[0]

array([1, 2, 3])

In [17]:
c = np.zeros((3,3), dtype="int32")

In [18]:
c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [19]:
c.dtype

dtype('int32')

In [22]:
c = np.ones((3,3), dtype="int32")

In [23]:
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [24]:
c = np.full((3,3), 50, dtype="int32")

In [25]:
c

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]], dtype=int32)

In [27]:
np.random.rand(4,4)

array([[0.15154148, 0.47975948, 0.00202587, 0.99484183],
       [0.21890789, 0.32410032, 0.27909073, 0.35676353],
       [0.45731092, 0.3447308 , 0.18263373, 0.41926773],
       [0.05310042, 0.81620419, 0.44429523, 0.294431  ]])

In [29]:
np.random.randint(0, 100, size=(3,3))

array([[ 9, 73, 14],
       [59, 79, 64],
       [68,  8,  8]], dtype=int32)

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
a = np.array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,7],
    [1,2,3,4,5,8],
    [1,2,3,4,5,9],
    [1,2,3,4,5,10]
     ])

In [54]:
a[:3, -5:]

array([[2, 3, 4, 5, 6],
       [2, 3, 4, 5, 7],
       [2, 3, 4, 5, 8]])

In [77]:
import math

In [87]:
def make_matrix_cross(n: int):
    cross = np.zeros((n,n), dtype="int32")

    middle_point = n//2

    cross[:, middle_point] = 1
    cross[middle_point, :] = 1

    return cross

In [89]:
answer = make_matrix_cross(3)

print(answer)

[[0 1 0]
 [1 1 1]
 [0 1 0]]


In [93]:
a = np.array([1,2,3,4])

a+2 #Non-descructive

array([3, 4, 5, 6])

In [97]:
a = a**3

In [98]:
a.min()

np.int64(1)

In [99]:
a.max()

np.int64(64)

In [100]:
a.mean()

np.float64(25.0)